spring:
  jpa:
    properties:
      hibernate:
        default_schema: jwt #public
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      ddl-auto: update # 数据库的操作模式
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
  datasource:
    username: jwt #postgres
    password: 12345678 #postgres
    url: jdbc:postgresql://127.0.0.1:5432/jwt?currentSchema=jwt
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.lhw: debug

rsa:
  key:
    pubKeyPath: E:\temp\jwt\auth_key\jwt_key_rsa.pub
    priKeyPath: E:\temp\jwt\auth_key\jwt_key_rsa